is_debug: true
dir:
    log: /data/logs/doctrinecache
    data: /data/doctrinecache
    cache: ./cache
    template: ./templates
db:
    host: localhost
    port: 3306
    user: doctrinecache
    password: doctrinecache
    dbname: doctrinecache
memcached:
    host: localhost
    port: 11211
aws:
    profile: doctrinecache
    region: cn-north-1
dynamodb:
    prefix: doctrinecache-
